CREATE TABLE [dbo].[Kill Bone trends graph TMP]
(
[Week] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[1] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[3] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[4] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[5] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[6] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[7] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[8] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[9] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[10] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[11] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[12] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[13] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[14] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[15] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[16] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[17] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[18] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[19] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[20] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[21] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[22] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[23] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[24] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[25] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[26] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[27] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[28] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[29] [varchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
